### ISSUE TITLE
Bundler not installing dependencies, failing the build

### ISSUE THREAD

**Issue by milosmns** [actions/jekyll-build-pages#105]
Hey, I do believe my issue is coming from this action.

I recently attempted to upgrade Jekyll (and related) dependencies for my blog, which then failed the build as a result: https://github.com/milosmns/milosmns.github.io/actions/runs/7600750931/job/20699353764

What happened exactly:

  - My local build failed due to bundler being incompatible with my ruby version
  - I decide to upgrade everything
  - SASS converter starts complaining that `/` (divide operator) is deprecated
  - I migrate to `math.div` instead
  - Local build passes
  - I push to GitHub
  - GitHub Pages action runs
  - 💣

I understand that there are some limitations with GH Actions and ruby/bundler versions, but as I'm really not an expert at that, I was hoping that you already have a workaround. I couldn't find anything in the closed issues that fully matches my problem.

Thanks for the support!

**Comment by vitalityglowlife** [comment]
same here

**Comment by yoannchaudet** [comment]
Hello!

This Action is a backward compatible layer with what Pages used to run in its legacy build infrastructure.

If you want to manage your dependencies and be much more free in that regards, please use such a workflow instead: https://github.com/actions/starter-workflows/blob/5241fd1653c9224b3623ff84b18d1d2081ec77b4/pages/jekyll.yml.

This will let you update to Jekyll 4 as well.
