### ISSUE TITLE
Outdated version of bundler

### ISSUE THREAD

**Issue by Laguna1989** [actions/jekyll-build-pages#109]
The version of bundler used with this github action is (2.1.4). According to the [bundler rubygems website](https://rubygems.org/gems/bundler/versions?locale=en) this is from January 2020 and by that already four years old. 

The latest version as of today is 2.5.5 from 2024-01-18.

This poses not only a big concern to supported features but can also mean a massive security risk.

I strongly advice to upgrade to the latest version as soon as possible and on a regular basis.

**Comment by yoannchaudet** [comment]
Should be better with https://github.com/actions/jekyll-build-pages/blob/e68e997ed1ead48e80ca5231b0b8ec8d0ce0dbcc/Dockerfile#L1-L2.

```
❯ docker run -it  ruby:3.3-slim  /bin/bash
root@05d8639a770d:/# bundle -v
Bundler version 2.5.11
```
