### ISSUE TITLE
.nojekyll being ignored

### ISSUE THREAD

**Issue by travisdowns** [actions/jekyll-build-pages#11]
I have a blog on github pages, which I build myself and push the generated static files to `gh-pages` brach in `docs` folder. This works great.

I don't want github to automatically build my pages, so I have a `.nojekyll` file as shown here:

https://github.com/travisdowns/travisdowns.github.io/tree/c90b37dd2eb59b9c2bc58f1a48d8380cd67dc481

Still, this action is running and publishing (at least per the logs) to github pages. 

How do I make it stop?

**Comment by parkr** [comment]
@travisdowns Hey! I don't think anyone is watching this repo, so the best bet is to email support@github.com and report this bug.

**Comment by yoannchaudet** [comment]
Hello, this repository is tracked but it has much less visibility at the moment (this will change) than the community forums.

I see you posted on https://github.community/t/jekyll-build-pages-running-despite-nojekll-file/223715/3 too. Thank you for that 🙇. Let us know if you run into further problems.

**Comment by travisdowns** [comment]
Yes, the comments there revealed the solution:

If you have your pages set to publish from the docs folder, you should have `.nojekyll` at `docs/.nojekyll` rather than at the root of the repository.
