### ISSUE TITLE
Struggling to host a txt file

### ISSUE THREAD

**Issue by tjrobinson** [actions/jekyll-build-pages#120]
I am trying to host a txt file using this action but struggling. Is there anything I can configure to get it to include txt files when generating the site?

The repository is:
https://github.com/tjrobinson/ageukreading-mta-sts/

The workflow is this, unaltered from the sample:
https://github.com/tjrobinson/ageukreading-mta-sts/blob/main/.github/workflows/jekyll-gh-pages.yml

I'm unable to get it to serve any of these files:

https://ma-sts.ageukreading.org.uk/test.txt
https://ma-sts.ageukreading.org.uk/testdir/test2.txt
https://ma-sts.ageukreading.org.uk/.well-known/ma-sts.txt

I can serve a HTML file though:

https://ma-sts.ageukreading.org.uk/htmltest.html

Many thanks!

**Comment by parkr** [comment]
Jekyll automatically removes files and directories that start with a dot. Add a _config.yml file with:

```
include:
- .well-known
```

Something like that would help the last TXT file. The others don't give me a 404.

**Comment by tjrobinson** [comment]
@parkr Thanks for your quick response. The other txt files work for me too - I probably tried them before they were fully deployed earlier.

I already had a `_config.yml` file - I've now updated it to match the format in your example but still not seeing the file in that directory unfortunately:

https://github.com/tjrobinson/ageukreading-mta-sts/blob/main/_config.yml

https://ma-sts.ageukreading.org.uk/.well-known/ma-sts.txt

**Comment by tjrobinson** [comment]
I was being an idiot - I was missing the T in MTA. So had been looking at `ma-sts.txt` not `mta-sts.txt`!

Started again, and it's all good now: https://github.com/tjrobinson/mta-sts.ageukreading.org.uk/
