### ISSUE TITLE
jekyll-build-pages uses an unsupported version of Ruby

### ISSUE THREAD

**Issue by jabenninghoff** [actions/jekyll-build-pages#123]
The [Dockerfile](https://github.com/actions/jekyll-build-pages/blob/main/Dockerfile) for jekyll-build-pages uses Ruby 2.7.4, which is no longer supported. This is causing GitHub Pages Jekyll builds to [fail](https://github.com/orgs/community/discussions/127006).

The GitHub [pages-gem](https://github.com/github/pages-gem) has been updated to Ruby 3.3, the [current stable version](https://www.ruby-lang.org/en/downloads/). Can jekyll-build-pages also be updated to use Ruby 3.3 (by updating the Dockerfile) and a new release deployed?

**Comment by jabenninghoff** [comment]
Fixing this will also resolve #109.

**Comment by jabenninghoff** [comment]
It also appears that https://github.com/github/pages-gem/pull/917 must be merged to update Ruby.

**Comment by yoannchaudet** [comment]
Should be fixed on `main` and about to go out with a new version.
