### ISSUE TITLE
there is no option to pass jekyll build options

### ISSUE THREAD

**Issue by zak905** [actions/jekyll-build-pages#126]
the jekyll build command can be configured with many options (they can be seen by running jekyll build --help). For example:

```
 --config CONFIG_FILE[,CONFIG_FILE2,...]  Custom configuration file
```

I usually pass multiple config files to jekyll depending on the environment I am deploying to. 

However this action do not provide a way to pass those options.

**Comment by yoannchaudet** [comment]
This Actions provide a "backward" compatible build process for running Jekyll the way we used to in GitHub's internal build infrastructure. We have no plans on extending functionalities on that side.

If you want to customize your build, the way to go is to stop using this action and instead use vanilla Jekyll with a workflow like [that one we document](https://github.com/actions/starter-workflows/blob/5241fd1653c9224b3623ff84b18d1d2081ec77b4/pages/jekyll.yml).

This way you will be able to use any plugins, any themes and more importantly Jekyll 4.
