### ISSUE TITLE
Any way opt out of the public beta?

### ISSUE THREAD

**Issue by larshp** [actions/jekyll-build-pages#2]
Hi,
Is there a way to not be part of the public beta?

My pages are breaking... https://github.com/actions/jekyll-build-pages/issues/3, https://github.com/actions/jekyll-build-pages/issues/4

**Comment by lautumn1990** [comment]
The same problem. How can I solve the problem?

**Comment by larshp** [comment]
@lautumn1990 in your case, which I guess is https://github.com/lautumn1990/blog/runs/4558598012?check_suite_focus=true, I've posted https://github.com/actions/jekyll-build-pages/issues/4 as it looks like you have a similar problem with the Gemfile being ignored

**Comment by yoannchaudet** [comment]
The only way (now that it has been fixed) is to disable Actions for the concerned repository.

**Comment by lautumn1990** [comment]
@larshp @yoannchaudet Thank you very much, it works!
