### ISSUE TITLE
If Actions are disabled for the repository, there are no error messages

### ISSUE THREAD

**Issue by larshp** [actions/jekyll-build-pages#3]
Before finding the change with the public beta, I had actions disabled on repository level. If actions are disabled, there are no error messages, in the in the pages configuration or when pushing to the branch to be deployed

![image](https://user-images.githubusercontent.com/5888506/146510515-1ab9e2e7-ebaa-4317-9893-7e0ca3f923bd.png)

found these under Actions after enabling actions for the repository,
![image](https://user-images.githubusercontent.com/5888506/146510483-8a6954e3-bf03-4afe-99af-349ff161d3f9.png)

**Comment by yoannchaudet** [comment]
Hello, this has just been fixed. When Actions is disabled (entirely), Pages build like before.
