### ISSUE TITLE
Gemfile is ignored in new build setup?

### ISSUE THREAD

**Issue by larshp** [actions/jekyll-build-pages#4]
Hi,
We have
https://github.com/abapGit/abapGit/tree/c0252083ffa46e6920ef9c4e797c6ffc75e01f5a/docs
with
https://github.com/abapGit/abapGit/blob/c0252083ffa46e6920ef9c4e797c6ffc75e01f5a/docs/Gemfile

moving this pages setup verbatim to the new setup gives the following error, see https://github.com/abapGit/docs.abapgit.org/runs/4557637625

![image](https://user-images.githubusercontent.com/5888506/146510921-63a25bed-fde3-4de6-9ff8-8cc8dc3f0ccf.png)

I expect the new build process to work for pages that previously worked?

**Comment by yoannchaudet** [comment]
Thank you for the report! This is being fixed now :)
