### ISSUE TITLE
Is Gemfile ignored now?

### ISSUE THREAD

**Issue by myst729** [actions/jekyll-build-pages#46]
I host my blog on github pages with jekyll.

In my [Gemfile](https://github.com/myst729/myst729.github.io/blob/master/Gemfile) I added a plugin. But it doesn't work as I expected. After some research I found the file was [excluded by the action](https://github.com/myst729/myst729.github.io/runs/7827543533?check_suite_focus=true#step:4:35).

What's the reason of doing so? And how could I add custom plugins? Adding `_plugins` fold might not be a good idea since the plugin has dependencies.

**Comment by yoannchaudet** [comment]
If you need full control over the build and use any plugins we may not allow in (https://github.com/github/pages-gem), please change your source to "GitHub Actions" and use this [starter workflow](https://github.com/actions/starter-workflows/blob/main/pages/jekyll.yml).

Your are using a legacy and compatible with what has been done up until now mechanism for building your Pages site currently. You can learn a bit more about this new thing in https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/.

**Comment by myst729** [comment]
Thanks. In the past 3 years I just randomly write things, haven't touch the build part for a long time. I also notice it's using Jekyll 3.9.x when I try some 4.x features. Maybe it's time for a "cognitive upgrade" 😆
