### ISSUE TITLE
Github Pages as Actions to run automatically in forked repos

### ISSUE THREAD

**Issue by vadimkantorov** [actions/jekyll-build-pages#54]
I successfully set up Actions pipeline from `starter-workflows` to replicate my classic Jekyll setup. However, these actions aren't run automatically in a forked repo. This was not the case with Classic pages, they would run&deploy in the forked repo automatically (especially, if the forked repo contained only gh-pages branch). Is there a way to replicate this behavior with Actions as well?

Basically, I'm building a website scaffolding/barebones that's intended to be forked. And ideally, it should already be enough and give a generated test webpage available online, without any extra configuration.

**Comment by vadimkantorov** [comment]
More than that, after enabling Actions in the forked repo, the forker must manually trigger a Pages build/deploy action, as no separate commit/push is there to trigger it. Mere enabling of Actions doesn't trigger the Pages build/deploy action

**Comment by vadimkantorov** [comment]
Also, the Pages settings is not Actions by default in the forked repo (and gets reset to Classic, especially if the forked repo has only gh-pages branch), even if it was enabled in the original repo

**Comment by yoannchaudet** [comment]
See https://github.com/orgs/community/discussions/30113#discussioncomment-4148636
