### ISSUE TITLE
Enabling plugins

### ISSUE THREAD

**Issue by brianary** [actions/jekyll-build-pages#63]
[About GitHub Pages and Jekyll - GitHub Docs](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#plugins) says that I should be able to add a plugin by name to the `plugins` value of _\_config.yml_, but that doesn't seem to work. It suggests getting more info from [Configuration | Jekyll • Simple, blog-aware, static sites](https://jekyllrb.com/docs/configuration/), which doesn't really cover that, but has a link to [Plugins | Jekyll • Simple, blog-aware, static sites](https://jekyllrb.com/docs/plugins/installation/) that tries to help, but is immediately mired in details about a _Gemfile_ and specifics that I don't have enough Ruby experience with to understand.

How do I add plugins like mermaid, AsciiDoc, &c?

**Comment by parkr** [comment]
> For a list of supported plugins, see "[Dependency versions](https://pages.github.com/versions/)" on the GitHub Pages site

The link lists the supported plugins. All other plugins are not supported. The documentation could be clearer on this point. The best thing to do IMO is to create a custom Actions workflow that builds with your dependencies / plugins and deploys to Pages. I'm not sure exactly the best way to do this these days but I'd recommend looking into a custom Pages build to use asciidoc, mermaid, etc. Someone who works at GitHub could be of more help :)

**Comment by brianary** [comment]
I guess I had misunderstood that switching from branch deployment to Actions deployment would add more flexibility. Thanks for pointing out that link, I guess I'd missed its relevance. I'll have to see if I can figure out an action to augment my Jekyll Action with an AsciiDoc processing step, and maybe something to preprocess Mermaid content.

Is there a GitHub repo that I could request additional plugin support at?

**Comment by parkr** [comment]
GitHub Support was historically the place to request. I do see some issues here: https://github.com/github/pages-gem/issues/684 https://github.com/github/pages-gem/issues/847

**Comment by brianary** [comment]
Cool, between that and [github/pages-gem #835](https://github.com/github/pages-gem/issues/835), I have a place to pursue this. Thanks!
