### ISSUE TITLE
Unable to pull docker image

### ISSUE THREAD

**Issue by gmorgan-ping** [actions/jekyll-build-pages#77]
Hi -

My GitHub actions have stopped working today as it's unable to retrieve the docker **ghcr.io/actions/jekyll-build-pages:v1.0.7**
Not sure if the image has moved or if there's another tag. I attempted latest, v1.0.8 with no luck.

Receiving the following message

`Error response from daemon: Head "https://ghcr.io/v2/actions/jekyll-build-pages/manifests/latest": Get "https://ghcr.io/token?scope=repository%3Aactions%2Fjekyll-build-pages%3Apull&service=ghcr.io": net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

Any assistance would be greatly appreciated!

**Comment by gmorgan-ping** [comment]
This appears to be a known issue as posted here https://www.githubstatus.com/incidents/ybnn77s3lyf8?utm_ts=1678891166

**Comment by ryepup** [comment]
If a search engine led you here, there's another incident: https://www.githubstatus.com/incidents/vsc464zj7gv4, should be fixed soonish
