### ISSUE TITLE
Link to documentation or include sample workflow YAML in README

### ISSUE THREAD

**Issue by parkr** [actions/jekyll-build-pages#78]
Hi friends!

I was looking at this repo and realized two quick things:

1. There's no link to the GitHub Pages section of the docs.github.com about how to use this action
2. There's no documentation at all about how to use this action

I think adding a new section like "Usage" with a link to the docs.github.com page for this would fit both needs, but it'd also be nice to have an example folks could copy-and-paste like what I see for setup-ruby: https://github.com/ruby/setup-ruby#usage

Thanks for considering! 

cc @yoannchaudet

**Comment by yoannchaudet** [comment]
Hello old friend!

We are "secretly" waiting for a rebranding of pages.github.com.

But that's no excuse to document now. Prioritizing that :)

**Comment by parkr** [comment]
Thank you!!
