### ISSUE TITLE
with future: false it is still showing all of my future blogs

### ISSUE THREAD

**Issue by rupeshtiwari** [actions/jekyll-build-pages#9]
From December end week `future: false` is not working. This was working previously. 

## Expected Behavior
I expected my site to not show the future blogs. I am using future: false.
Here is my action link https://github.com/rupeshtiwari/rupeshtiwari.github.io/actions
Check it is showing all of my future blogs https://www.rupeshtiwari.com/posts/

## Current Behavior
It is showing all of the future dated blogs check this blog
https://www.rupeshtiwari.com/posts/
Here is my config file
https://github.com/rupeshtiwari/rupeshtiwari.github.io/blob/main/_config.yml

**Comment by canro91** [comment]
Same here. I tried adding a secret and environment var with INPUT_FUTURE set to 'false'. But that doesn't seem to work. Is there a way to stop building the site with '--future' flag? Thanks

**Comment by parkr** [comment]
I followed up in a recent PR: https://github.com/actions/jekyll-build-pages/pull/6#discussion_r780690150

Basically, the `--Future` flag overrides the config. It should be a default, not an override.

**Comment by rupeshtiwari** [comment]
Thanks @parkr  can you let me know what is the work around to fix this issue. This is a huge problem. There must be some workaround till they fix this issue. please help.

**Comment by rupeshtiwari** [comment]
> Same here. I tried adding a secret and environment var with INPUT_FUTURE set to 'false'. But that doesn't seem to work. Is there a way to stop building the site with '--future' flag? Thanks

I also recently created both environment & secrete variable `INPUT_FUTURE`  but 
 it did not work. Not sure what did they change this is recent issue. It used to work nicely. 
https://github.com/rupeshtiwari/rupeshtiwari.github.io/runs/4750988619?check_suite_focus=true

**Comment by yoannchaudet** [comment]
Alright a bit of context first.

## Context

We did https://github.com/actions/jekyll-build-pages/pull/6 to bring back the default behavior that we had missed earlier where legacy Pages builds where always defaulting to having the `--future` option set to true in response to a couple support tickets we received. The original decision around future was made [back in 2016](https://github.com/github/pages-gem/pull/302) and kind of make sense to me.

Pages are always rebuilt when new commits are made to a repository. So having a post publication date set in the future does not necessarily mean this post will become live at that specific date (and time) if no commits are made to the repository.

Behind https://github.com/actions/jekyll-build-pages/pull/6, we introduced an input so users will be able to stay way from our default "soon" (i.e. we plan on letting people define their own Actions workflow to make Pages deployments so full customization will be possible then).

Now we also missed (!) that users could override the behavior by setting `future: true` in their Jekyll configuration file...

## What we don't want

In the legacy way of building Pages sites (understand where Actions is not involved)
## What we propose

**Comment by yoannchaudet** [comment]
Alright a bit of context first.

## Context

We did https://github.com/actions/jekyll-build-pages/pull/6 to bring back the default behavior that we had missed earlier where legacy Pages builds where always defaulting to having the `--future` option set to true in response to a couple support tickets we received. The original decision around future was made [back in 2016](https://github.com/github/pages-gem/pull/302) and kind of make sense to me.

Pages are always rebuilt when new commits are made to a repository. So having a post publication date set in the future does not necessarily mean this post will become live at that specific date (and time) if no commits are made to the repository.

Behind https://github.com/actions/jekyll-build-pages/pull/6, we introduced an input so users will be able to stay way from our default "soon" (i.e. we plan on letting people define their own Actions workflow to make Pages deployments so full customization will be possible then).

Now we also missed (!) that users could override the behavior by setting `future: false` in their Jekyll configuration file...

## What I don't want

In the legacy way of building Pages sites (understand where Actions is not involved), we do some serious work on your Jekyll configuration files. We read it, sanitize a bunch of things, force a few things, set some default, etc.. This is very intrusive and sensitive but also the only way to maintain security in that part of the system. With the move to Actions we can and did part away from all this code (Actions provides us a good trust boundary for the builds). Without this entire logic we are also getting closer to a "vanilla" Jekyll experience (sure we are still lagging behind, but this is another problem we will tackle separately).

I unfortunately don't see a way to properly get `future` to be true for everyone by default but also support override in the configuration without bringing back our code that would meddle with the configuration file (or worse, do some changes on Jekyll side to support that).

## What I propose

Given there seems to be more issues having `future` defaulting to `true` and the fact that currently this behavior cannot be overwritten, I propose to remove it and go back to the [default Jekyll sets (i.e. `false`)](https://jekyllrb.com/docs/upgrading/2-to-3/#future-posts).

This is what was happening when we initially released our new builds with Actions.

There are a few gotchas to get Jekyll to publish posts at a given date but the feature is working nicely:

- You really want to specify a `timezone` in your Jekyll configuration file and not rely on what the Actions runner will give you
- If you specify a date time in your front matter (you should), it also needs to include a timezone offset

---

**Any objections?**

**Comment by BenSouchet** [comment]
If I understand correctly your proposition is to remove the `future` input of this action (i.e. `jekyll-build-pages`) and let the value of `future` be  set in the `_config.yml`, is that it?
If the user hasn't set `future` in is `_config.yml` file the default value from Jekyll is `false`.

I'm personally okay with that, since the closer Jekyll Github Pages are from Jekyll the better.

**Comment by parkr** [comment]
@yoannchaudet Thamks for the detailed context! Another solution you can consider is using Jekyll's `--config` flag. It accepts a comma-separated list of files and reads them one by one, merging later files over earlier ones. This would allow you to preserve the desired behavior by writing a config file of defaults, then merging the user's configs on top.

It would be really interesting to see how many users notice this. Going toward a more "vanilla" Jekyll experience is desirable. I do foresee the lack of timezone data causing unexpected bugs for anyone in the eastern hemisphere so I'm not sure removing the future flag here achieves your goal of mimicking the user's local environment so long as actions runners are set to a time zone behind the user's. If Actions could get the user's local timezone somehow, then this problem could be solved for 99% of cases. (Just don't travel great distances too often!)

**Comment by parkr** [comment]
I see you're running `github-pages Build` so you could easily set some defaults in that ruby code!

**Comment by rupeshtiwari** [comment]
Thanks @everyone. these are all good discussion. I am okay with not defining future in config  file and framework will keep future default value as false during build. However, question is when this will be fixed? Meanwhile is there any fix that I can do in my repo to not show my future posts. My downstream sites which read feeds and display blocks are broken since they started showing posts from future dates. This is very much breaking show stopper issue. 

Can anyone reply when this will be fixed? 
What is the temporary solution to fix so that future blogs will not show up?

**Comment by parkr** [comment]
@rupeshtiwari The quickest way to solve this is to add `published: false` to the posts that you don't want to publish yet. Add that to the YAML front matter of each post. Or, move the files to another directory and move back when you're ready to post.

**Comment by rupeshtiwari** [comment]
Thanks @parkr  I have around 100s of post its not easy for me to change all of them for now. I build the site locally and published from a separate branch that way I just fixed my site. I am waiting till we fix this issue.

**Comment by yoannchaudet** [comment]
I'll get a partial revert of https://github.com/actions/jekyll-build-pages/pull/6 deployed this week to revert to Jekyll's default (of `false`) for the `future` option. Sorry for the long wait on this one. Been busy on the IRL side the past few days 😑.
